name: ci

on:
  push:
    branches: master

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $username -p $password
      - name: Build and push
        run: docker build . --file Dockerfile --tage sreesaram/mtom-server:latest
        
      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USERNAME}}/sreesaran
