  
name: Test Dockerhub Push
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Copy Repo Files
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build and Publish Docker image to Dockerhub
        uses: ./
        with:
          TAG: 'latest'
          DOCKERFILE_PATH: 'Dockerfile'
          BUILD_CONTEXT: '.'
          DOCKERHUB_REPOSITORY: 'sreesaran/mtom-server'
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        env:
          REGISTRY_TOKEN: ${{ secrets.DOCKERHUB_SECRET }}
